### ISSUE TITLE
 Failed at the hiredis@0.1.17 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by andrewmolo** [redis/hiredis-node#121]
I am having this issue while setting up cartoDB server locally. Kindly assist. Thanks a lot. 

[npm-debug.txt](https://github.com/redis/hiredis-node/files/249476/npm-debug.txt)

**Comment by badboy** [comment]
Please upgrade hiredis. Latest released version is v0.4.1. 0.1.17 is unsupported and will not work with newer Node versions.

**Comment by andrewmolo** [comment]
When I run  `npm install --loglevel=verbose hiredis` I see the version is v0.4.1. See image, where could I be going wrong?
 
![hiredis](https://cloud.githubusercontent.com/assets/1729842/15076141/cc0c7e48-13b0-11e6-874c-868e298f4c9a.png)

**Comment by badboy** [comment]
The image shows that it installed without problems.
