### ISSUE TITLE
Support for existing system-level hiredis installation?

### ISSUE THREAD

**Issue by mindpivot** [redis/hiredis-node#132]
Hi there!

I was wondering if it'd be possible to have this library use an existing installation of hiredis to prevent the need to have gcc+/python libs installed on the system when installing hiredis-node, if the underlying system already has the proper version of hiredis installed.

The reasoning for this is to prevent the need to fully re-build the package inside a docker container. If an existing installation could be used, one of the docker file build steps could simply be to just install hiredis through the distribution package manager (Alpine in this case). The build tools needed to install hiredis-node add ~250MB to the size of a container, whereas using the native package manager version seems to only add roughly 27MB. The ability to use an existing version of the library would be a huge container optimization win.

Thanks!

**Comment by badboy** [comment]
There's a thin layer of C++ code wrapping hiredis, which would need to be compiled, so you'd still need a compiler and its libs.

**Comment by mindpivot** [comment]
Understood. Thank you for the quick reply! Much appreciated!
