### ISSUE TITLE
npm install hiredis failed on windows 10 x64

### ISSUE THREAD

**Issue by perfmlin** [redis/hiredis-node#133]
@fuwaneko

.node-gyp\6.10.0\Release\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x648
30 [E:\nst\aliyun\NstApp\node_modules\hiredis\build\hiredis.vcxproj]

![qq 20170523202339](https://cloud.githubusercontent.com/assets/10769151/26354097/c808d298-3ff5-11e7-9d5e-d7e11465f220.png)

![qq 20170523201312](https://cloud.githubusercontent.com/assets/10769151/26353732/55209f82-3ff4-11e7-972f-4c539758e6a6.png)

**Comment by badboy** [comment]
Please, if possible, post log output as text. It's indexable, searchable and accessible. Images are not.

Did you check if your disk is actually full? Did you check if the file it tries to access exists and is not garbage?

I don't have any Windows machine to test on and rely on appveyor for CI tests. I thus cannot provide more detailed support with a Windows-only issue apart from what I can read from the logs.

**Comment by perfmlin** [comment]
@badboy 
Thanks for you reply so fast. My disk is not full and there are more than one TB left. I also checked that the file is not access exists.
bellow is the log file:

[install.txt](https://github.com/redis/hiredis-node/files/1022156/install.txt)

**Comment by badboy** [comment]
As I said: I have no experience with Windows, so I don't know how to fix it (besides googling the error message and try out suggested fixes.
If you find a way to fix this, please leave a message.

Which version of Visual Studio have you installed?

**Comment by dolugen** [comment]
Yep, looks like a disk space problem. @badboy Are you looking at the correct partition? It appears that `hiredis` is being installed in disk `E`.
