### ISSUE TITLE
Does this only work with g++ or does it work with clang

### ISSUE THREAD

**Issue by jloveric** [redis/hiredis-node#136]
Does this also work with clang?  If not, seems like it should - though I'm, not sure if this is a limitation of gyp or this particular package.

**Comment by jloveric** [comment]
Apparently it does, since g++ points to clang on macosx, which I'm using.  On linux it tries to pick up g++ even if only clang is available.  Is it possible to fix this in this module so it also works with clang?

**Comment by badboy** [comment]
hiredis(-node) does nothing special in that regard and completely relies on `gyp` to do its work. Whatever C++ and C compiler matching more or less what gcc 4.8 is doing will work (that includes any recent clang++)
Setting `CXX=clang++ CC=clang` in your environment or simply linking the name to the right compiler could work.
