### ISSUE TITLE
install error in win7 64bit

### ISSUE THREAD

**Issue by flyzb618** [redis/hiredis-node#61]
181 info install bindings@1.2.0 into D:\test\node_modules\hiredis
182 info install nan@1.1.2 into D:\test\node_modules\hiredis
183 info installOne bindings@1.2.0
184 info installOne nan@1.1.2
185 info D:\test\node_modules\hiredis\node_modules\bindings unbuild
186 info D:\test\node_modules\hiredis\node_modules\nan unbuild
187 verbose tar unpack D:\node\node-cache\bindings\1.2.0\package.tgz
188 silly lockFile db4056c0-es-hiredis-node-modules-bindings tar://D:\test\node_modules\hiredis\node_modules\bindings
189 verbose lock tar://D:\test\node_modules\hiredis\node_modules\bindings D:\node\node-cache\db4056c0-es-hiredis-node-modules-bindings.lock
190 silly lockFile b6f390a0-cache-bindings-1-2-0-package-tgz tar://D:\node\node-cache\bindings\1.2.0\package.tgz
191 verbose lock tar://D:\node\node-cache\bindings\1.2.0\package.tgz D:\node\node-cache\b6f390a0-cache-bindings-1-2-0-package-tgz.lock
192 verbose tar unpack D:\node\node-cache\nan\1.1.2\package.tgz
193 silly lockFile d7142ba3-modules-hiredis-node-modules-nan tar://D:\test\node_modules\hiredis\node_modules\nan
194 verbose lock tar://D:\test\node_modules\hiredis\node_modules\nan D:\node\node-cache\d7142ba3-modules-hiredis-node-modules-nan.lock
195 silly lockFile eaa321ed-node-cache-nan-1-1-2-package-tgz tar://D:\node\node-cache\nan\1.1.2\package.tgz
196 verbose lock tar://D:\node\node-cache\nan\1.1.2\package.tgz D:\node\node-cache\eaa321ed-node-cache-nan-1-1-2-package-tgz.lock
197 silly gunzTarPerm modes [ '755', '644' ]
198 silly gunzTarPerm modes [ '755', '644' ]
199 silly gunzTarPerm extractEntry package.json
200 silly gunzTarPerm modified mode [ 'package.json', 438, 420 ]
201 silly gunzTarPerm extractEntry package.json
202 silly gunzTarPerm modified mode [ 'package.json', 438, 420 ]
203 silly gunzTarPerm extractEntry README.md
204 silly gunzTarPerm modified mode [ 'README.md', 438, 420 ]
205 silly gunzTarPerm extractEntry LICENSE
206 silly gunzTarPerm modified mode [ 'LICENSE', 438, 420 ]
207 silly gunzTarPerm extractEntry README.md
208 silly gunzTarPerm modified mode [ 'README.md', 438, 420 ]
209 silly gunzTarPerm extractEntry bindings.js
210 silly gunzTarPerm modified mode [ 'bindings.js', 438, 420 ]
211 silly gunzTarPerm extractEntry include_dirs.js
212 silly gunzTarPerm modified mode [ 'include_dirs.js', 438, 420 ]
213 silly gunzTarPerm extractEntry .dntrc
214 silly gunzTarPerm modified mode [ '.dntrc', 438, 420 ]
215 silly gunzTarPerm extractEntry build/config.gypi
216 silly gunzTarPerm modified mode [ 'build/config.gypi', 438, 420 ]
217 silly gunzTarPerm extractEntry nan.h
218 silly gunzTarPerm modified mode [ 'nan.h', 438, 420 ]
219 silly lockFile db4056c0-es-hiredis-node-modules-bindings tar://D:\test\node_modules\hiredis\node_modules\bindings
220 silly lockFile db4056c0-es-hiredis-node-modules-bindings tar://D:\test\node_modules\hiredis\node_modules\bindings
221 silly lockFile b6f390a0-cache-bindings-1-2-0-package-tgz tar://D:\node\node-cache\bindings\1.2.0\package.tgz
222 silly lockFile b6f390a0-cache-bindings-1-2-0-package-tgz tar://D:\node\node-cache\bindings\1.2.0\package.tgz
223 info preinstall bindings@1.2.0
224 verbose readDependencies using package.json deps
225 verbose readDependencies using package.json deps
226 silly resolved []
227 verbose about to build D:\test\node_modules\hiredis\node_modules\bindings
228 info build D:\test\node_modules\hiredis\node_modules\bindings
229 verbose linkStuff [ false,
229 verbose linkStuff   false,
229 verbose linkStuff   false,
229 verbose linkStuff   'D:\\test\\node_modules\\hiredis\\node_modules' ]
230 info linkStuff bindings@1.2.0
231 verbose linkBins bindings@1.2.0
232 verbose linkMans bindings@1.2.0
233 verbose rebuildBundles bindings@1.2.0
234 info install bindings@1.2.0
235 info postinstall bindings@1.2.0
236 silly lockFile d7142ba3-modules-hiredis-node-modules-nan tar://D:\test\node_modules\hiredis\node_modules\nan
237 silly lockFile d7142ba3-modules-hiredis-node-modules-nan tar://D:\test\node_modules\hiredis\node_modules\nan
238 silly lockFile eaa321ed-node-cache-nan-1-1-2-package-tgz tar://D:\node\node-cache\nan\1.1.2\package.tgz
239 silly lockFile eaa321ed-node-cache-nan-1-1-2-package-tgz tar://D:\node\node-cache\nan\1.1.2\package.tgz
240 info preinstall nan@1.1.2
241 verbose readDependencies using package.json deps
242 verbose readDependencies using package.json deps
243 silly resolved []
244 verbose about to build D:\test\node_modules\hiredis\node_modules\nan
245 info build D:\test\node_modules\hiredis\node_modules\nan
246 verbose linkStuff [ false,
246 verbose linkStuff   false,
246 verbose linkStuff   false,
246 verbose linkStuff   'D:\\test\\node_modules\\hiredis\\node_modules' ]
247 info linkStuff nan@1.1.2
248 verbose linkBins nan@1.1.2
249 verbose linkMans nan@1.1.2
250 verbose rebuildBundles nan@1.1.2
251 info install nan@1.1.2
252 info postinstall nan@1.1.2
253 verbose about to build D:\test\node_modules\hiredis
254 info build D:\test\node_modules\hiredis
255 verbose linkStuff [ false, false, false, 'D:\\test\\node_modules' ]
256 info linkStuff hiredis@0.1.17
257 verbose linkBins hiredis@0.1.17
258 verbose linkMans hiredis@0.1.17
259 verbose rebuildBundles hiredis@0.1.17
260 verbose rebuildBundles [ 'bindings', 'nan' ]
261 info install hiredis@0.1.17
262 verbose unsafe-perm in lifecycle true
263 info hiredis@0.1.17 Failed to exec install script
264 info D:\test\node_modules\hiredis unbuild
265 info preuninstall hiredis@0.1.17
266 info uninstall hiredis@0.1.17
267 verbose true,D:\test\node_modules,D:\test\node_modules unbuild hiredis@0.1.17
268 info postuninstall hiredis@0.1.17
269 error hiredis@0.1.17 install: `node-gyp rebuild`
269 error Exit status 1
270 error Failed at the hiredis@0.1.17 install script.
270 error This is most likely a problem with the hiredis package,
270 error not with npm itself.
270 error Tell the author that this fails on your system:
270 error     node-gyp rebuild
270 error You can get their info via:
270 error     npm owner ls hiredis
270 error There is likely additional logging output above.
271 error System Windows_NT 6.1.7601
272 error command "D:\\node\\\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "hiredis"
273 error cwd D:\test
274 error node -v v0.10.26
275 error npm -v 1.4.6
276 error code ELIFECYCLE
277 verbose exit [ 1, true ]

**Comment by badboy** [comment]
I have no way to test Windows support, so I'm not really in favour of patching this in. But I will think about it.

**Comment by XVincentX** [comment]
@badboy 
You could just setup [Appveyorn](http://www.appveyor.com), that will ensure that Windows support will always be working.

**Comment by badboy** [comment]
Thanks, I'll take a look.

**Comment by XVincentX** [comment]
@badboy Any update on this? I may take care of that (merging changes from fork and setup appveyorn) if you think it can speed up the things.

**Comment by badboy** [comment]
I will release a new version of Hiredis this weekend and only after that I will take on the Windows support.

**Comment by XVincentX** [comment]
Ok, let me know if I can help somehow.

**Comment by badboy** [comment]
Thanks, I will get back to you

**Comment by badboy** [comment]
So small update on this: I finally found some time playing around with appveyor and already got hiredis-py build running (and succeeding) there. I will continue this work in the following weeks and hopefully we have builds for hiredis-{py,node,rb} on Windows soon.

**Comment by XVincentX** [comment]
@badboy Amazing! Can't wait to see it merged!

**Comment by badboy** [comment]
@XVincentX the latest commit should enable to work on Windows, could you try? I still need to properly set up appveyor for this

**Comment by XVincentX** [comment]
@badboy I will definitely try this as soon as possible and write here the results.

**Comment by badboy** [comment]
Thanks, currently a test is running here: https://ci.appveyor.com/project/badboy/hiredis-node-win/build/job/wj6an5trhy4iou4g

**Comment by badboy** [comment]
I released a new version, it should work on Windows now. Please reopen if not.
