### ISSUE TITLE
build errors once node-gyp kicks in, due to multiple build solutions.

### ISSUE THREAD

**Issue by Pomax** [redis/hiredis-node#65]
```
> hiredis@0.1.17 install C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\makedrive\node_modules\hired
is
> node-gyp rebuild


C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\makedrive\node_modules\hiredis>node "C:\Program Files
\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\makedrive\node_modules\hiredis\build\binding.sln : S
olution file error MSB5004: The solution file has two projects named "hiredis".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
67:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\Users\Mike\Documents\Git projects\collaborations\webmaker-suite\makedrive\node_modules\hiredis
gyp ERR! node -v v0.10.30
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm WARN optional dep failed, continuing hiredis@0.1.17
```

**Comment by Pomax** [comment]
Did this issue get fixed, or did it just get accidentally closed?

**Comment by badboy** [comment]
We currently do not have Windows support. I have no Windows machine to reproduce.
There is a fork, https://github.com/fuwaneko/hiredis-node, that could maybe help.

**Comment by Pomax** [comment]
that ... kind of doesn't sound like a good enough reason to close a legitimate issue? This is the "officially sanctioned" redis for node.

**Comment by badboy** [comment]
No support for Windows = nothing I can do to help here.
If we ever integrate Windows support, I'll make sure it actually works. But for now we just don't support it. Sorry.

**Comment by Pomax** [comment]
that's fine, but by closing with that rationale you're also saying "and we aren't interested in people who do have windows and are willing to help us solve this problem do so for us", which is disappointing =(

This is probably an issue that someone familiar with node-gyp and does use windows can solve without even needing to understand the code itself (because if you don't have a windows dev path, then clearly this is an issue that pops up only once node-gyp kicks in, not your code having multiple microsoft visual studio solution files, because why would you have those if you don't support windows?)

I'd still strongly recommend keeping this bug open just in case someone who *can* fix it sees it and is motivated enough to send you a PR that fixes it.

**Comment by badboy** [comment]
First: sorry for closing the issue without a comment in the first place.
We have a hiredis-node fork that includes Windows support. If it breaks their, please report it there. 

As this repo here does not bundle Windows support, it's not really an issue for now.

**Comment by Pomax** [comment]
it's a problem as long as that alternative also claims to be `hiredis`: https://www.npmjs.com/package/hiredis points here, without any mention that on windows you actually need a completely different package. It gets even hairier for projects that use the `hiredis` code dependency, because npm doesn't install different packages for different OS, and there is no mechanism to "overload" a dependency for npm so that the right package gets installed.

I was going to suggest updating the README.md to tell windows users they need `npm install git://github.com/fuwaneko/hiredis-node`, but fuwaneko's fork also doesn't compile on windows, so is not an actual solution =(

**Comment by mattsta** [comment]
Another potential solution: ask/get the MSOpenTech people to either fix it or take responsibility for windows versions of all clients.

**Comment by badboy** [comment]
@Pomax the README already includes a link to the Windows port

**Comment by Pomax** [comment]
clearly I didn't scroll down enough. It'll have to do! thanks for the responses.
