### ISSUE TITLE
Instructions on how to run the tests

### ISSUE THREAD

**Issue by thedrow** [redis/hiredis-node#68]
We're testing all the bindings with each new commit on hiredis master.
I need help to run the tests and there are no instructions on the readme file on how to do so.

**Comment by stephank** [comment]
Not a committer, but for what it's worth, this is done with `npm test`.

**Comment by thedrow** [comment]
I still can't run the tests:
https://travis-ci.org/redis/hiredis/jobs/43193298

**Comment by stephank** [comment]
Oh, there's a Makefile. I'd never seen that before. But is seems, to me, unnecessary.

You don't need to install `node-gyp` either. From a clean checkout, install submodules, then run `npm install` in the directory, followed by `npm test`.

**Comment by thedrow** [comment]
I'll give it a shot.

**Comment by badboy** [comment]
any help needed here? Please reopen then.
