### ISSUE TITLE
change redis timeout

### ISSUE THREAD

**Issue by chasrmartin** [redis/hiredis-node#69]
I have a situation where I'm getting redis timeouts repeatably on one page of my application.  What's involved is an express connection to a back end, using hiredis-node. 

I'm tracking down the actual performance issue, but in the mean time, the application is pretty much unusable.  How can I change the timeout?

**Comment by stephank** [comment]
The `hiredis` connection object is also just a `net.Socket`. So what you could try is enabling TCP keepalives, see: http://nodejs.org/api/net.html#net_socket_setkeepalive_enable_initialdelay)

Redis itself also has `timeout` option in its configuration, see: http://redis.io/topics/clients

Beyond that, you can send a `PING` at an interval, but if you're saying your performance issue stalls the main loop, then that won't help much. (Maybe you can look into off-loading the calculation from the main loop?)
