### ISSUE TITLE
Install fails on Windows 8 with unstable/latest Python versions

### ISSUE THREAD

**Issue by Nessworthy** [redis/hiredis-node#80]
Installed an experimental copy of python, npm install yields: 

    gyp ERR! UNCAUGHT EXCEPTION
    gyp ERR! stack TypeError: Invalid Version: 3.5.0a3
    gyp ERR! stack     at new SemVer ([...]\node_modules\npm\node_modules\semver\semver.js:271:11)
    gyp ERR! stack     at compare ([...]\node_modules\npm\node_modules\semver\semver.js:424:10)
    gyp ERR! stack     at gte ([...]\node_modules\npm\node_modules\semver\semver.js:473:10)
    gyp ERR! stack     at cmp ([...]\node_modules\npm\node_modules\semver\semver.js:490:22)
    gyp ERR! stack     at Comparator.test ([...]\node_modules\npm\node_modules\semver\semver.js:560:10)
    gyp ERR! stack     at testSet ([...]\node_modules\npm\node_modules\semver\semver.js:894:17)
    gyp ERR! stack     at Range.test ([...]\node_modules\npm\node_modules\semver\semver.js:886:9)
    gyp ERR! stack     at [...]\node_modules\npm\node_modules\node-gyp\lib\configure.js:94:17
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:645:7)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    gyp ERR! System Windows_NT 6.2.9200
    gyp ERR! command "node" "[...]\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd [..project..]\node_modules\hiredis
    gyp ERR! node -v v0.10.28
    gyp ERR! node-gyp -v v0.13.0
    gyp ERR! This is a bug in `node-gyp`.
    gyp ERR! Try to update node-gyp and file an Issue if it does not help:
    gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
    npm ERR! hiredis@0.3.0 install: `node-gyp rebuild`
    npm ERR! Exit status 7

I figure it's just dying parsing the version string because of the format of the alpha releases. I'll be re-installing a stable version of Python to counter it but just thought I'd give a heads up. :smile:

**Comment by badboy** [comment]
Thanks for the report, though there's not much I can do, this is a bug in the node build tools. I'm not even sure the build tools even work with stable Python 3.
You could still report this upstream to see if they want to fix it.

**Comment by Nessworthy** [comment]
No worries, thanks for responding! I downgraded to `3.4.3` and received:
`gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.`
I'll report this upstream as suggested. Thanks!
