### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by steelbrain** [redis/hiredis-node#85]
How fast is it? and how slow are pure js parsers?
'cause I have [a parser][parser] too in Pure JS and less than 50 lines of code, which doesn't need any kind-of compilation.
I am sure it's pretty fast too.
[parser]:https://github.com/steelbrain/Redis-Proto/blob/master/Source/Main.js

**Comment by badboy** [comment]
There's a `bench.js` included, run it and compare to your own ;)

**Comment by steelbrain** [comment]
Don't get me wrong but that `bench.js` code is `un-beautiful`. Who even wrote that thing :\

**Comment by badboy** [comment]
That would be easy to find out. You're free to provide your own and share the results with us. I'm currently to busy to do this by myself
