### ISSUE TITLE
Build failing on iojs?

### ISSUE THREAD

**Issue by taoeffect** [redis/hiredis-node#88]
Our app is failing to build on Travis all of a sudden under iojs because of an error with hiredis.

I've copied the log here: http://pastebin.com/geq8N3r1

**Comment by taoeffect** [comment]
Oh I see you've released two versions since 0.2. I will go ahead and update and close this issue if that fixes it.

**Comment by taoeffect** [comment]
All good! Thanks for fixing this. :)

**Comment by badboy** [comment]
You're welcome!
