### ISSUE TITLE
can't install hiredis on io.js 2.3.0 controlled by nvm

### ISSUE THREAD

**Issue by zhaoyao91** [redis/hiredis-node#89]
my environment is OS X 10.10.3 (14D136)，nvm，io.js 2.3.0
when I tried to install by typing 'sudo npm install --save hiredis', some problem occured:
> hiredis@0.4.0 install /Users/zhaoyao-code/workspace/ydcy/email-auth/node_modules/hiredis
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.3.0/node-v2.3.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/zhaoyao-code/.nvm/versions/io.js/v2.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/zhaoyao-code/.nvm/versions/io.js/v2.3.0/lib/node_modules/npm/node_modules/request/request.js:1142:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/zhaoyao-code/.nvm/versions/io.js/v2.3.0/bin/iojs" "/Users/zhaoyao-code/.nvm/versions/io.js/v2.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zhaoyao-code/workspace/ydcy/email-auth/node_modules/hiredis
gyp ERR! node -v v2.3.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/zhaoyao-code/.nvm/versions/io.js/v2.3.0/bin/iojs" "/Users/zhaoyao-code/.nvm/versions/io.js/v2.3.0/bin/npm" "install" "--save" "hiredis"
npm ERR! node v2.3.0
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiredis@0.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhaoyao-code/workspace/ydcy/email-auth/npm-debug.log

**Comment by badboy** [comment]
All this node/io.js is a mess. Somehow the wrong node-gyp is invoked, we had the same problem on Travis. For you this might work: https://github.com/redis/hiredis-node/pull/84#issuecomment-99553356

**Comment by bkw** [comment]
updating nan to ~1.8.4 works for me.
