### ISSUE TITLE
0.4.0 fails with iojs v3.0.0

### ISSUE THREAD

**Issue by taoeffect** [redis/hiredis-node#95]
I'm not sure whether this is related to #94, but I know this:

- Travis [uses Python 2.7 by default](http://docs.travis-ci.com/user/languages/python/) and we don't override that.
- It builds for nodejs 0.10 and 0.12
- It fails for iojs 3.0.0

See the full error/build log here:

https://travis-ci.org/okTurtles/dnschain/jobs/74161603

**Comment by badboy** [comment]
Gnaaah, they keep breaking nan with new io.js releases. Upgrading nan should do the trick.

**Comment by badboy** [comment]
Except that nan 2 breaks lots of other stuff. I put this on my todo, hopefully until the end of the week.

**Comment by badboy** [comment]
Guess this have to wait for a bit. There is no documentation on the upgrade process for NAN v2 (yet).

**Comment by taoeffect** [comment]
Are we sure this issue is fixed?

Travis still erroring with it: https://travis-ci.org/okTurtles/dnschain/jobs/77775121

**Comment by badboy** [comment]
Atleast our own build didn't fail: https://travis-ci.org/redis/hiredis-node/jobs/76797442

I'll look into this tomorrow.

**Comment by badboy** [comment]
@taoeffect I can't reproduce it locally. It builds just fine for me with the latest io.js. Even a `npm install` in your dnschain project works (after changing it to latest hiredis-node, not sure where your commit for this ended up)

**Comment by taoeffect** [comment]
@badboy This appears due to a difference between our `.travis.yml` files. Yours [explicitly installs g++-4.8](https://github.com/redis/hiredis-node/blob/master/.travis.yml), whereas ours uses [the default settings](https://github.com/okTurtles/dnschain/blob/master/.travis.yml).

So, since most people don't customize their `.travis.yml` file in this way, is it possible to make it work with the defaults? If not, perhaps you can update your README to instruct people that `hiredis` requires making customizations to `.travis.yml`?

**Comment by badboy** [comment]
Thanks for checking, I see what I can do about it.

**Comment by badboy** [comment]
Latest node/io.js has gcc/g++ 4.8 as a prerequisite.
gcc 4.6, which is the default on travis, is more than 3 years old, so moving on seems reasonable.

I will add it to the readme.

**Comment by taoeffect** [comment]
Awesome, thanks @badboy!

**Comment by NicolasRitouet** [comment]
I had the same issue on CircleCI with hiredis 0.4.1 on node 4.2.0.
Adding this to `circle.yml` fixed the problem:
```
machine:
  pre:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 10
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 10
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
```

Thanks @badboy
